// Internationalization (i18n) system for Lithuanian and English
const translations = {
    lt: {
        // Start Menu
        'app.title': 'Quizleris',
        'menu.welcome': 'Sveiki atvykę į Quizleris',
        'menu.selectRole': 'Pasirinkite savo vaidmenį:',
        'menu.student': 'Esu Mokinys',
        'menu.admin': 'Esu Administratorius',
        'menu.dashboard': 'Peržiūrėti Rezultatus',
        'menu.heroHeadline': 'Pradėk žaisti dabar',
        'menu.pinPlaceholder': 'Įvesk žaidimo PIN / ID...',
        'menu.pinGo': 'Pradėti →',
        'menu.divider': 'arba',
        'menu.discover': 'Atrask testus',
        // Student Form
        'student.nameLabel': 'Jūsų vardas (neprivaloma)',
        'student.namePlaceholder': 'Įveskite vardą rezultatų sekimui',
        'student.premadeLabel': 'Išbandykite paruoštą testą:',
        'student.quizIdLabel': 'Arba įveskite testo kodą / ID',
        'student.quizIdPlaceholder': 'demo',
        'student.startBtn': 'Pradėti testą',
        'student.backBtn': 'Atgal',
        // Admin Panel
        'admin.title': 'Sukurti/Redaguoti testą',
        'admin.dashboard': 'Rezultatai',
        'admin.backToMenu': 'Atgal į meniu',
        'admin.quizTitle': 'Testo pavadinimas:',
        'admin.quizTitlePlaceholder': 'Mano matematikos testas',
        'admin.timerMode': 'Laikmačio režimas:',
        'admin.timerPerQuestion': 'Laikas kiekvienam klausimui',
        'admin.timerWholeQuiz': 'Laikas visam testui',
        'admin.timerNone': 'Be laikmačio (Chronometras)',
        'admin.timeLimit': 'Laiko limitas (sekundės):',
        'admin.addQuestion': 'Pridėti klausimą',
        'admin.scanQuestion': '📷 Nuskaityti klausimą (OCR)',
        'admin.saveQuiz': 'Išsaugoti testą',
        'admin.exportJson': 'Eksportuoti JSON',
        'admin.importJson': 'Importuoti JSON',
        'admin.preview': 'Peržiūra',
        'admin.cancel': 'Atšaukti',
        'res_vis_label': 'Rezultato matomumas:',
        'res_vis_det': 'Išsami peržiūra (klausimai ir atsakymai)',
        'res_vis_sco': 'Tik galutinis balas',
        'admin.question': 'Klausimas',
        'admin.qType': 'Klausimo tipas:',
        'admin.typeMC': 'Pasirinkimo variantai',
        'admin.typeNum': 'Skaitinis atsakymas',
        'admin.typeBlank': 'Užpildyti tuščias vietas',
        'admin.typeImage': 'Nuotraukos įkėlimas',
        'admin.typeText': 'Tekstinis atsakymas',
        'admin.typeTF': 'Taip / Ne',
        'admin.mcMultiple': 'Leisti kelis teisingus atsakymus',
        'admin.numAnswer': 'Teisingas skaičius:',
        'admin.numTolerance': 'Paklaida:',
        'admin.tolAbs': 'Absoliuti (±vnt)',
        'admin.tolPct': 'Procentinė (±%)',
        'admin.blankAnswers': 'Atsakymai tuščioms vietoms (___):',
        'admin.keywords': 'Raktiniai žodžiai (atskirti kableliu):',
        'admin.longAnswer': 'Ilgas atsakymas',
        'admin.isTrue': 'Teisingas atsakymas yra Taip',
        'admin.imageUploadHint': 'Studentas matys mygtuką nuotraukos įkėlimui. Vertinama bus rankiniu būdu.',
        'admin.addImage': 'Pridėti nuotrauką',
        'admin.removeImage': 'Pašalinti nuotrauką',
        'admin.blankHint': 'Instrukcija: Naudokite ___ (trys pabraukimo brūkšniai) užpildymo vietoms.',
        'admin.insertBlank': 'Įterpti tarpą (___)',
        'admin.shuffleConfig': 'Maišymo nustatymai:',
        'admin.shuffleQuestions': 'Maišyti klausimus',
        'admin.shuffleAnswers': 'Maišyti atsakymų variantus',
        'admin.quizMode': 'Testo režimas:',
        'admin.modePractice': 'Praktika (Rezultatas po klausimo pateikimo)',
        'admin.modeExam': 'Egzaminas (rezultatai po pateikimo)',
        'admin.promptLabel': 'Klausimas (LaTeX):',
        'admin.addChoice': 'Pridėti pasirinkimą',
        'admin.removeQuestion': 'Pašalinti klausimą',
        'admin.removeChoice': 'Ištrinti pasirinkimą',
        'admin.quizSaved': 'Testas išsaugotas!',
        'admin.shareUrl': 'Dalintis nuoroda:',
        'admin.quizId': 'Testo ID:',
        'admin.copyLink': 'Kopijuoti nuorodą',
        // Alerts
        'alert.deleteQuestion': 'Ar tikrai norite ištrinti šį klausimą?',
        'alert.deleteChoice': 'Pašalinti šį pasirinkimą?',
        'alert.addOneQuestion': 'Pridėkite bent vieną klausimą!',
        'alert.allQuestionsPrompt': 'Visi klausimai turi turėti klausimą!',
        'alert.twoChoicesMin': 'Kiekvienas klausimas turi turėti bent 2 pasirinkimus!',
        'alert.oneCorrectAnswer': 'Kiekvienas klausimas turi turėti bent vieną teisingą atsakymą!',
        'alert.quizNotFound': 'Testas su tokiu ID nerastas.',
        'alert.ocrAdded': 'Klausimas pridėtas iš skenavimo! Peržiūrėkite ir pažymėkite teisingą atsakymą.',
        'alert.ocrError': 'Klaida apdorojant vaizdą. Bandykite dar kartą arba įveskite rankiniu būdu.',
        'alert.importSuccess': 'Testas sėkmingai importuotas!',
        'alert.invalidJson': 'Netinkamas testo JSON.',
        'alert.jsonParseError': 'Klaida analizuojant JSON',
        'alert.clearHistory': 'Ar tikrai norite išvalyti visą istoriją?',
        'alert.linkCopied': 'Nuoroda nukopijuota!',
        // Dashboard
        'dashboard.title': 'Rezultatų suvestinė',
        'dashboard.recentActivity': 'Naujausia veikla',
        'dashboard.highScores': 'Geriausi rezultatai',
        'dashboard.date': 'Data',
        'dashboard.name': 'Vardas',
        'dashboard.quiz': 'Testas',
        'dashboard.score': 'Rezultatas',
        'dashboard.topStudent': 'Geriausias mokinys',
        'dashboard.noResults': 'Rezultatų dar nėra.',
        'dashboard.backToMenu': 'Atgal į meniu',
        'dashboard.clearHistory': 'Išvalyti istoriją',
        // Quiz UI Flow
        'quiz.question': 'Klausimas',
        'quiz.of': 'iš',
        'quiz.score': 'Rezultatas',
        'quiz.time': 'Laikas',
        'quiz.correct': 'Teisingai!',
        'quiz.incorrect': 'Neteisingai',
        'quiz.timesUp': 'Laikas pasibaigė!',
        'quiz.chooseAnswer': 'Pasirinkite atsakymą',
        'quiz.nextQuestion': 'Kitas klausimas',
        'quiz.complete': 'Testas baigtas!',
        'quiz.viewResults': 'Peržiūrėti rezultatus',
        'quiz.takeAgain': 'Bandyti dar kartą',
        'quiz.backToMenu': 'Atgal į meniu',
        'quiz.correctAnswer': 'Teisingas atsakymas',
        'quiz.noAnswer': 'Neatsakyta',
        'quiz.mcSelectOne': 'Pasirinkite vieną',
        'quiz.mcSelectAll': 'Pasirinkite visus tinkamus',
        'quiz.examSubmit': 'Pateikti egzaminą',
        'quiz.examConfirm': 'Ar tikrai norite baigti egzaminą ir pateikti atsakymus?',
        'quiz.answered': 'atsakyta',
        'quiz.pending': 'Laukiama vertinimo',
        'quiz.previewFinished': 'Peržiūra baigta — galite uždaryti šį skirtuką.',
        'quiz.jumpTo': 'Eiti į',
        'quiz.backBtn': 'Atgal',
        'quiz.backConfirm': 'Ar tikrai norite grįžti? Testas bus prarastas.',
        // Quiz Titles
        'quiz.demoTitle': 'Bandomasis testas',
        'quiz.algebraTitle': 'Algebros pagrindai',
        'quiz.combinatoricsTitle': 'Kombinatorikos iššūkis',
        // Join Screen
        'admin.adminMode': 'Administratoriaus režimas',
        'admin.playerMode': 'Žaidėjo režimas',
        'admin.newQuiz': 'Naujas testas',
        'admin.timerUpdateError': 'Laikmačio atnaujinimo klaida',
        'admin.prompt': 'Klausimas (LaTeX)',
        'admin.confirmRemoveQuestion': 'Ar tikrai norite ištrinti šį klausimą?',
        'admin.confirmRemoveChoice': 'Pašalinti šį pasirinkimą?',
        'admin.untitledQuiz': 'Pavadinimas neįvestas',
        'admin.errorNoQuestions': 'Pridėkite bent vieną klausimą!',
        'admin.errorNoPrompt': 'Visi klausimai turi turėti klausimą!',
        'admin.errorNoChoices': 'Kiekvienas klausimas turi turėti bent 2 pasirinkimus!',
        'admin.errorNoCorrect': 'Kiekvienas klausimas turi turėti bent vieną teisingą atsakymą!',
        'admin.saveSuccess': 'Testas sėkmingai išsaugotas!',
        'admin.studentUrl': 'Nuoroda mokiniams',
        'admin.copy': 'Kopijuoti',
        'admin.dashboardUrl': 'Administratoriaus suvestinės nuoroda',
        'admin.importSuccess': 'Testas sėkmingai importuotas!',
        'admin.importInvalid': 'Netinkamas testo JSON.',
        'admin.importError': 'Klaida analizuojant JSON',
        'admin.confirmCancel': 'Ar tikrai norite atšaukti? Visi neįrašyti pakeitimai bus prarasti.',
        'admin.previewName': 'Peržiūra',
        'admin.closePreview': 'Uždaryti peržiūrą',
        // Join Screen
        'join.joinQuiz': 'Prisijungti prie testo:',
        'join.questions': 'klausimai',
        'join.yourName': 'Jūsų vardas',
        'join.namePlaceholder': 'Įveskite savo vardą',
        'join.startBtn': 'Pradėti testą',
        'join.backBtn': 'Atgal',
        // Detailed Dashboard
        'dashboard.actions': 'Veiksmai',
        'dashboard.details': 'Detalės',
        'dashboard.closeDetails': 'Uždaryti',
        'dashboard.resultDetail': 'Rezultato informacija:',
        'dashboard.selected': 'Pasirinkta',
        'dashboard.noDetails': 'Išsamių duomenų apie šį rezultatą nėra.',
        'dashboard.unified': 'Sukurti Testai',
        'dashboard.time': 'Visas laikas',
        'dashboard.avgTime': 'Vid. laikas per klausimą',
        'dashboard.review': 'Peržiūra',
        'topics.title': 'Paruoštų testų temos',
        'student.premadeEnglish': 'Anglų kalbos paruošti testai',
        'student.premadeLithuanianSoon': 'Lietuviški paruošti testai',
        'student.premadeLithuanianHint': 'Lietuviški paruošti testai',
        // Premium Expansion Keys
        'topics.categories.all': 'Visi',
        'topics.categories.math': 'Matematika ir Fizika',
        'topics.categories.lang': 'Kalbos ir įvairenybės',
        'topics.categories.cs': 'Informatika',
        'modal.playTitle': 'Pasirinkite žaidimo režimą',
        'modal.practiceDesc': 'Tinkama mokymuisi: atsakymo patikrinimas iškart su paaiškinimais.',
        'modal.timeAttackDesc': 'Azartiškas režimas: ribotas laikas visam testui, skubėkite!',
        'modal.examDesc': 'Formalus egzaminas: rezultatai rodomi tik užbaigus visą testą.',
        'modal.playBtn': 'Pradėti!',
        'modal.highScore': 'Geriausias rezultatas',
        'admin.livePreview': 'Gyva LaTeX / Teksto peržiūra:',
        'admin.duplicate': 'Dubliuoti',
        'admin.moveUp': 'Aukštyn',
        'admin.moveDown': 'Žemyn',
        'admin.bulkImport': 'Masinis importas (Tekstas)',
        'admin.bulkImportTitle': 'Įveskite klausimus masiniam importui',
        'admin.bulkImportHint': 'Naudokite formatą:\nQ: Klausimo tekstas\nA) Pirmas variantas\n*B) Antras variantas (teisingas, su *)\nC) Trečias variantas\n\nSkirkite klausimus tuščia eilute.',
        'admin.importBtn': 'Importuoti',
        'admin.duplicateSuccess': 'Klausimas sėkmingai nukopijuotas!',
        'theme.emerald': '\u0160viesus Fonas',
        'theme.slateDark': 'Tamsus Fonas',
        'theme.cyberpunk': 'Tamsus Fonas\u00b2',
        'theme.solar': 'Tamsus Fonas\u00b3',
        'quiz.streak': '🔥 STREAKAS',
        'quiz.xpEarned': 'Gauti taškai (XP)',
        'quiz.rank': 'Pasiektas Rangas!',
        'rank.novice': 'Naujokas 🥬',
        'rank.novice.desc': 'Tikras naujokas! 🥬 Dar yra kur pasistengti, bet pradžia padaryta!',
        'rank.apprentice': 'Mokinys 📖',
        'rank.apprentice.desc': 'Mokinys — jau geriau! 📖 Knygos po pagalve pradeda veikti!',
        'rank.adept': 'Ekspertas 🧠',
        'rank.adept.desc': 'Ekspertas! 🧠 Tavo smegenų vingiai dirba visu pajėgumu!',
        'rank.master': 'Meistras ⚡',
        'rank.master.desc': 'Tikras meistras! ⚡ Klasė nuščiuvo, mokytojas verkia iš laimės.',
        'rank.genius': 'Mokslo Genijus 🌌',
        'rank.genius.desc': 'Mokslo Genijus! 🌌 Tavo IQ viršija kosmoso greitį, Einsteinas ploja atsistojęs!',
        'admin.draftSaved': 'Juodraštis išsaugotas',
        'admin.savingDraft': 'Saugomas juodraštis...',
        'admin.draftDetected': 'Rastas neišsaugotas juodraštis! Ar norite jį atkurti?',
        'admin.restore': 'Atkurti',
        'admin.dismiss': 'Atmesti',
        'admin.loadSavedQuiz': '-- Įkelti išsaugotą testą --',
        'admin.deleteConfirm': 'Ar tikrai norite ištrinti šį išsaugotą testą iš savo įrenginio?',
        'admin.latexPaletteTitle': 'LaTeX & Simboliai',
        'admin.paletteTabCommon': 'Prasti',
        'admin.paletteTabGreek': 'Graikų',
        'admin.paletteTabOperators': 'Operatoriai',
        'admin.paletteTabAdvanced': 'Sudėtingi',
        'admin.shortcutsTitle': 'Greitieji klavišai',
        'admin.shortcutSave': 'Išsaugoti',
        'admin.shortcutNew': 'Naujas kl.',
        'admin.shortcutWrap': 'LaTeX apgaub.',
        'admin.shortcutUndoRedo': 'Atšaukti/Grąžinti',
        'admin.selectFieldFirst': 'Spustelėkite klausimo įvesties arba pasirinkimo lauką!',
    },
    en: {
        // Start Menu
        'app.title': 'Quizleris',
        'menu.welcome': 'Welcome to Quizleris',
        'menu.selectRole': 'Please select your role:',
        'menu.student': "I'm Student",
        'menu.admin': "I'm Admin",
        'menu.dashboard': 'View Dashboard',
        'menu.heroHeadline': 'Start playing now',
        'menu.pinPlaceholder': 'Enter game PIN / ID...',
        'menu.pinGo': 'Start →',
        'menu.divider': 'or',
        'menu.discover': 'Discover quizzes',
        // Student Form
        'student.nameLabel': 'Your Name (optional)',
        'student.namePlaceholder': 'Enter name to track results',
        'student.premadeLabel': 'Try a Premade Quiz:',
        'student.quizIdLabel': 'Or Enter Quiz Code / ID',
        'student.quizIdPlaceholder': 'demo',
        'student.startBtn': 'Start Quiz',
        'student.backBtn': 'Back',
        // Admin Panel
        'admin.title': 'Create/Edit Quiz',
        'admin.dashboard': 'Dashboard',
        'admin.backToMenu': 'Back to Menu',
        'admin.quizTitle': 'Quiz Title:',
        'admin.quizTitlePlaceholder': 'My Math Quiz',
        'admin.timerMode': 'Timer Mode:',
        'admin.timerPerQuestion': 'Time per Question',
        'admin.timerWholeQuiz': 'Time for Whole Quiz',
        'admin.timerNone': 'No Timer (Stopwatch)',
        'admin.timeLimit': 'Time Limit (seconds):',
        'admin.addQuestion': 'Add Question',
        'admin.scanQuestion': '📷 Scan Question (OCR)',
        'admin.saveQuiz': 'Save Quiz',
        'admin.exportJson': 'Export JSON',
        'admin.importJson': 'Import JSON',
        'admin.preview': 'Preview',
        'admin.cancel': 'Cancel',
        'res_vis_label': 'Result Visibility:',
        'res_vis_det': 'Detailed Review (Questions & Answers)',
        'res_vis_sco': 'Score Only',
        'admin.question': 'Question',
        'admin.qType': 'Question Type:',
        'admin.typeMC': 'Multiple Choice',
        'admin.typeNum': 'Numeric Answer',
        'admin.typeBlank': 'Fill in the Blank',
        'admin.typeImage': 'Image Upload',
        'admin.typeText': 'Text Answer',
        'admin.typeTF': 'True / False',
        'admin.mcMultiple': 'Allow multiple correct answers',
        'admin.numAnswer': 'Correct Number:',
        'admin.numTolerance': 'Tolerance:',
        'admin.tolAbs': 'Absolute (±val)',
        'admin.tolPct': 'Percentage (±%)',
        'admin.blankAnswers': 'Answers for blanks (___):',
        'admin.keywords': 'Keywords (comma separated):',
        'admin.longAnswer': 'Long answer',
        'admin.isTrue': 'Correct answer is True',
        'admin.imageUploadHint': 'Student will see a button to upload a photo. This requires manual grading.',
        'admin.addImage': 'Add Image',
        'admin.removeImage': 'Remove Image',
        'admin.blankHint': 'Instruction: Use ___ (three underscores) for blanks.',
        'admin.insertBlank': 'Insert Blank (___)',
        'admin.shuffleConfig': 'Shuffle Settings:',
        'admin.shuffleQuestions': 'Shuffle Questions',
        'admin.shuffleAnswers': 'Shuffle Choices',
        'admin.quizMode': 'Quiz Mode:',
        'admin.modePractice': 'Practice (Result after submission)',
        'admin.modeExam': 'Exam (results after submission)',
        'admin.promptLabel': 'Prompt (LaTeX):',
        'admin.addChoice': 'Add Choice',
        'admin.removeQuestion': 'Remove Question',
        'admin.removeChoice': 'Delete choice',
        'admin.quizSaved': 'Quiz saved!',
        'admin.shareUrl': 'Share URL:',
        'admin.quizId': 'Quiz ID:',
        'admin.copyLink': 'Copy Link',
        // Alerts
        'alert.deleteQuestion': 'Are you sure you want to delete this specific question?',
        'alert.deleteChoice': 'Remove this choice?',
        'alert.addOneQuestion': 'Add at least one question!',
        'alert.allQuestionsPrompt': 'All questions must have a prompt!',
        'alert.twoChoicesMin': 'Each question needs at least 2 choices!',
        'alert.oneCorrectAnswer': 'Each question needs at least one correct answer!',
        'alert.quizNotFound': 'Quiz not found with that ID.',
        'alert.ocrAdded': 'Question added from scan! Review and mark the correct answer.',
        'alert.ocrError': 'Error processing image. Please try again or type manually.',
        'alert.importSuccess': 'Quiz imported successfully!',
        'alert.invalidJson': 'Invalid quiz JSON.',
        'alert.jsonParseError': 'Error parsing JSON',
        'alert.clearHistory': 'Are you sure you want to clear all history?',
        'alert.linkCopied': 'Link copied!',
        // Dashboard
        'dashboard.title': 'Results Dashboard',
        'dashboard.recentActivity': 'Recent Activity',
        'dashboard.highScores': 'High Scores',
        'dashboard.date': 'Date',
        'dashboard.name': 'Name',
        'dashboard.quiz': 'Quiz',
        'dashboard.score': 'Score',
        'dashboard.topStudent': 'Top Student',
        'dashboard.noResults': 'No results recorded yet.',
        'dashboard.backToMenu': 'Back to Menu',
        'dashboard.clearHistory': 'Clear History',
        // Quiz UI Flow
        'quiz.question': 'Question',
        'quiz.of': 'of',
        'quiz.score': 'Score',
        'quiz.time': 'Time',
        'quiz.correct': 'Correct!',
        'quiz.incorrect': 'Incorrect',
        'quiz.timesUp': "Time's Up!",
        'quiz.chooseAnswer': 'Choose an answer',
        'quiz.nextQuestion': 'Next Question',
        'quiz.complete': 'Quiz Complete!',
        'quiz.viewResults': 'View Results',
        'quiz.takeAgain': 'Take Quiz Again',
        'quiz.backToMenu': 'Back to Menu',
        'quiz.correctAnswer': 'Correct Answer',
        'quiz.noAnswer': 'No Answer',
        'quiz.mcSelectOne': 'Select one',
        'quiz.mcSelectAll': 'Select all that apply',
        'quiz.examSubmit': 'Submit Exam',
        'quiz.examConfirm': 'Are you sure you want to finish the exam and submit your answers?',
        'quiz.answered': 'answered',
        'quiz.pending': 'Pending Review',
        'quiz.previewFinished': 'Preview finished — you can close this tab.',
        'quiz.jumpTo': 'Jump to',
        'quiz.backBtn': 'Back',
        'quiz.backConfirm': 'Are you sure you want to go back? Your quiz progress will be lost.',
        // Quiz Titles
        'quiz.demoTitle': 'Demo Quiz',
        'quiz.algebraTitle': 'Algebra Basics',
        'quiz.combinatoricsTitle': 'Combinatorics Challenge',
        // Join Screen
        'admin.adminMode': 'Admin Mode',
        'admin.playerMode': 'Player Mode',
        'admin.newQuiz': 'New Quiz',
        'admin.timerUpdateError': 'Timer update error',
        'admin.prompt': 'Prompt (LaTeX)',
        'admin.confirmRemoveQuestion': 'Are you sure you want to delete this specific question?',
        'admin.confirmRemoveChoice': 'Remove this choice?',
        'admin.untitledQuiz': 'Untitled Quiz',
        'admin.errorNoQuestions': 'Add at least one question!',
        'admin.errorNoPrompt': 'All questions must have a prompt!',
        'admin.errorNoChoices': 'Each question needs at least 2 choices!',
        'admin.errorNoCorrect': 'Each question needs at least one correct answer!',
        'admin.saveSuccess': 'Quiz saved successfully!',
        'admin.studentUrl': 'Student Share URL',
        'admin.copy': 'Copy',
        'admin.dashboardUrl': 'Admin Dashboard URL',
        'admin.importSuccess': 'Quiz imported successfully!',
        'admin.importInvalid': 'Invalid quiz JSON.',
        'admin.importError': 'Error parsing JSON',
        'admin.confirmCancel': 'Are you sure you want to cancel? Any unsaved changes will be lost.',
        'admin.previewName': 'Preview',
        'admin.closePreview': 'Close Preview',
        // Join Screen
        'join.joinQuiz': 'Join Quiz:',
        'join.questions': 'questions',
        'join.yourName': 'Your Name',
        'join.namePlaceholder': 'Enter your name',
        'join.startBtn': 'Start Quiz',
        'join.backBtn': 'Back',
        // Detailed Dashboard
        'dashboard.actions': 'Actions',
        'dashboard.details': 'Details',
        'dashboard.closeDetails': 'Close',
        'dashboard.resultDetail': 'Result Detail:',
        'dashboard.selected': 'Selected',
        'dashboard.noDetails': 'No detailed data available for this result.',
        'dashboard.unified': 'Created Quizzes',
        'dashboard.time': 'Total Time',
        'dashboard.avgTime': 'Avg Time per Question',
        'dashboard.review': 'Review',
        'topics.title': 'Premade Quiz Topics',
        'student.premadeEnglish': 'English Premade Quizzes',
        'student.premadeLithuanianSoon': 'Lithuanian Premade Quizzes',
        'student.premadeLithuanianHint': 'Lithuanian Premade Quizzes',
        // Premium Expansion Keys
        'topics.categories.all': 'All',
        'topics.categories.math': 'Math & Physics',
        'topics.categories.lang': 'Languages & Trivia',
        'topics.categories.cs': 'Computer Science',
        'modal.playTitle': 'Select Play Mode',
        'modal.practiceDesc': 'Best for learning: instant feedback and answer explanations.',
        'modal.timeAttackDesc': 'Exciting mode: tight time limit for the entire quiz, hurry up!',
        'modal.examDesc': 'Formal exam: final grade is revealed only after full submission.',
        'modal.playBtn': 'Play Now!',
        'modal.highScore': 'High Score',
        'admin.livePreview': 'Live LaTeX / Text Preview:',
        'admin.duplicate': 'Clone',
        'admin.moveUp': 'Move Up',
        'admin.moveDown': 'Move Down',
        'admin.bulkImport': 'Bulk Text Import',
        'admin.bulkImportTitle': 'Enter Questions for Bulk Import',
        'admin.bulkImportHint': 'Use format:\nQ: Question text\nA) First choice\n*B) Second choice (correct, starts with *)\nC) Third choice\n\nSeparate questions with an empty line.',
        'admin.importBtn': 'Import',
        'admin.duplicateSuccess': 'Question duplicated successfully!',
        'quiz.streak': '🔥 STREAK',
        'quiz.streakMultiplier': 'Streak Multiplier!',
        'theme.label': 'Theme:',
        'theme.emerald': 'Light Classic',
        'theme.slateDark': 'Dark Mode',
        'theme.cyberpunk': 'Dark Mode\u00b2',
        'theme.solar': 'Dark Mode\u00b3',
        'quiz.xpEarned': 'Experience Points (XP)',
        'quiz.rank': 'Rank Achieved!',
        'rank.novice': 'Novice 🥬',
        'rank.novice.desc': 'A true rookie! 🥬 There is room for improvement, but the journey has begun!',
        'rank.apprentice': 'Apprentice 📖',
        'rank.apprentice.desc': 'Apprentice — getting better! 📖 The books under your pillow are starting to work!',
        'rank.adept': 'Adept 🧠',
        'rank.adept.desc': 'Adept! 🧠 Your brain cells are firing at maximum capacity!',
        'rank.master': 'Master ⚡',
        'rank.master.desc': 'A true master! ⚡ The class fell silent, the teacher is crying tears of joy.',
        'rank.genius': 'Science Genius 🌌',
        'rank.genius.desc': 'Science Genius! 🌌 Your IQ exceeds the speed of light, Einstein is standing and applauding!',
        'admin.draftSaved': 'Draft Saved',
        'admin.savingDraft': 'Saving Draft...',
        'admin.draftDetected': 'Unsaved draft detected! Would you like to restore it?',
        'admin.restore': 'Restore',
        'admin.dismiss': 'Dismiss',
        'admin.loadSavedQuiz': '-- Load Saved Quiz --',
        'admin.deleteConfirm': 'Are you sure you want to delete this saved quiz from your device?',
        'admin.latexPaletteTitle': 'LaTeX & Symbols',
        'admin.paletteTabCommon': 'Common',
        'admin.paletteTabGreek': 'Greek',
        'admin.paletteTabOperators': 'Operators',
        'admin.paletteTabAdvanced': 'Advanced',
        'admin.shortcutsTitle': 'Keyboard Shortcuts',
        'admin.shortcutSave': 'Save',
        'admin.shortcutNew': 'New Question',
        'admin.shortcutWrap': 'LaTeX Math Wrap',
        'admin.shortcutUndoRedo': 'Undo/Redo',
        'admin.selectFieldFirst': 'Please click a question input or choice field first!',
    }
};
let currentLanguage = 'lt'; // Default to Lithuanian
// Initialize language from localStorage or default
export function initLanguage() {
    const saved = localStorage.getItem('quiz_language');
    if (saved && (saved === 'lt' || saved === 'en')) {
        currentLanguage = saved;
    }
}
// Get current language
export function getLanguage() {
    return currentLanguage;
}
// Set language and persist
export function setLanguage(lang) {
    currentLanguage = lang;
    localStorage.setItem('quiz_language', lang);
}
// Translate a key
export function t(key) {
    return translations[currentLanguage][key] || key;
}
// Update all translatable elements in the DOM
export function updatePageLanguage() {
    // Save current values of all select elements to prevent resets during option updates
    const selectStates = new Map();
    document.querySelectorAll('select').forEach(select => {
        selectStates.set(select, select.value);
    });

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n')?.trim();
        if (key) {
            el.textContent = t(key);
        }
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder')?.trim();
        if (key && el instanceof HTMLInputElement) {
            el.placeholder = t(key);
        }
    });

    // Restore saved select values
    selectStates.forEach((savedValue, select) => {
        select.value = savedValue;
    });
}
